version: "3.9"

networks:
  editorial-net:
    driver: bridge

volumes:
  authors-db-data:
  publications-db-data:

services:

  # ===============================
  # DATABASE AUTHORS (PostgreSQL)
  # ===============================
  db-authors:
    image: postgres:15
    container_name: db-authors
    env_file:
    - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - authors-db-data:/var/lib/postgresql/data
    networks:
      - editorial-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ===============================
  # DATABASE PUBLICATIONS (MySQL)
  # ===============================
  db-publications:
    image: mysql:8.0
    container_name: db-publications
    env_file:
    - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - publications-db-data:/var/lib/mysql
    networks:
      - editorial-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ===============================
  # AUTHORS SERVICE
  # ===============================
  authors-service:
    build: ./authors-service
    container_name: authors-service
    env_file:
    - .env
    depends_on:
      db-authors:
        condition: service_healthy
    ports:
      - "8081:8081"
    networks:
      - editorial-net
    environment:
      SPRING_PROFILES_ACTIVE: docker

  # ===============================
  # PUBLICATIONS SERVICE
  # ===============================
  publications-service:
    build: ./publications-service
    container_name: publications-service
    env_file:
    - .env
    depends_on:
      db-publications:
        condition: service_healthy
      authors-service:
        condition: service_started
    ports:
      - "8082:8082"
    networks:
      - editorial-net
    environment:
      SPRING_PROFILES_ACTIVE: docker

  # ===============================
  # FRONTEND
  # ===============================
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env.docker
    depends_on:
      - authors-service
      - publications-service
    networks:
      - editorial-net
