spring:
  application:
    name: authors-service

  datasource:
    url: jdbc:postgresql://localhost:5432/db-authors
    username: postgres
    password: 1995
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081